# 构建 linux arm64 版本的包，需要兼容 GLIBC_2.19
# 使用 Debian 8 (jessie) 作为容器基础镜像，可确保生成二进制最低 GLIBC 需求为 2.19。
# 若使用 Ubuntu 20.04，glibc 为 2.31，无法满足 GLIBC_2.19 的目标。
name: Linux Build ARM

on:
  workflow_dispatch:

jobs:
  build-linux-aarch64:
    runs-on: ubuntu-22.04-arm
    container: debian:8
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Fix APT sources (Debian 8 EOL)
        run: |
          set -eux
          cat >/etc/apt/sources.list <<'EOF'
          deb http://archive.debian.org/debian jessie main contrib non-free
          deb http://archive.debian.org/debian-security jessie/updates main contrib non-free
          EOF
          echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99no-check-valid-until
          echo 'Acquire::AllowInsecureRepositories "true";' > /etc/apt/apt.conf.d/99allow-insecure
          apt-get -o Acquire::Check-Valid-Until=false -o Acquire::AllowInsecureRepositories=true update

      - name: Install basic tools and dependencies
        run: |
          apt-get -o Acquire::Check-Valid-Until=false -o Acquire::AllowInsecureRepositories=true update
          apt-get install -y --no-install-recommends --allow-unauthenticated \
             git wget curl ca-certificates xz-utils unzip \
             build-essential pkg-config ninja-build nasm \
             autoconf automake libtool python3 python3-pip python3-setuptools python3-wheel \
             zlib1g-dev libjpeg-dev libudev-dev \
             libsdl2-2.0-0 libsdl2-dev \
             libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev \
             libusb-1.0-0 libusb-1.0-0-dev \
             libv4l-0 libv4l-dev libv4lconvert0 \
             libdigest-sha-perl

      - name: Install pip and meson compatible with Python 3.4
        run: |
          python3 -m ensurepip --default-pip || true
          python3 -m pip install --upgrade 'pip<19.2'
          python3 -m pip install 'setuptools==43.0.0' 'wheel==0.33.6'
          python3 -m pip install 'meson==0.49.2' --no-use-pep517


      - name: Check architecture
        run: |
            arch=$(uname -m)
            if [[ "$arch" != "aarch64" && "$arch" != "arm64" ]]
            then
                echo "Unexpected architecture: $arch" >&2
                exit 1
            fi

      - name: Check GLIBC version
        run: |
          ldd --version | head -n1 || true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build
        run: release/build_linux.sh aarch64

      # upload-artifact does not preserve permissions
      - name: Tar
        run: |
          cd release/work/build-linux-aarch64
          mkdir dist-tar
          cd dist-tar
          tar -C .. -cvf dist.tar.gz dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-linux-aarch64-intermediate
          path: release/work/build-linux-aarch64/dist-tar/
