# 构建 linux arm64 版本的包，需要支持 GLIBC_2.28
# container: ubuntu:20.04 构建出来最低的 GLIBC 版本是 2.29
name: Linux Build ARM

on:
  workflow_dispatch:

jobs:
  build-linux-aarch64:
    runs-on: ubuntu-22.04-arm
    container: ubuntu:18.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Install basic tools and dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends \
             git wget curl ca-certificates xz-utils unzip \
             build-essential pkg-config meson ninja-build nasm \
             autoconf automake libtool \
             zlib1g-dev libjpeg-dev libudev-dev \
             ffmpeg libsdl2-2.0-0 libsdl2-dev \
             libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev \
             libswresample-dev libusb-1.0-0 libusb-1.0-0-dev \
             libv4l-0 libv4l-dev libv4lconvert0 \
             libdigest-sha-perl


      - name: Check architecture
        run: |
            arch=$(uname -m)
            if [[ "$arch" != aarch64 && "$arch" != arm64 ]]
            then
                echo "Unexpected architecture: $arch" >&2
                exit 1
            fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build
        run: release/build_linux.sh aarch64

      # upload-artifact does not preserve permissions
      - name: Tar
        run: |
          cd release/work/build-linux-aarch64
          mkdir dist-tar
          cd dist-tar
          tar -C .. -cvf dist.tar.gz dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-linux-aarch64-intermediate
          path: release/work/build-linux-aarch64/dist-tar/
